  version "3.9"
  services:
    mysql:
      image: mysql:latest
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_ROOT_HOST=%
        - MYSQL_DATABASE=user
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "3306:3306"
    server:
      build:
        context: .
        dockerfile: Dockerfile
      image: server
      container_name: server
      ports:
        - "5050:5050"
      restart: "no"